### ISSUE TITLE
memory problems

### ISSUE THREAD

**Issue by yestoall** [mattdonnelly/MDHTMLLabel#10]
i'm having memory problems allocating MDHTMLLabels in TableCellViews.
have you experience this kind of errors?

**Comment by mattdonnelly** [comment]
I haven't encountered this myself, but if you send me a example project demonstrating the problem I'll be happy to look in to it

**Comment by yestoall** [comment]
now it works perfect... but i need to test more.

i'm using your code on a rubymotion project, and is a big one... difficult to share my testing problems.

great work.
thanks for your work.

**Comment by yestoall** [comment]
after more testing i detect that font inherit is not working

label.font = [UIFont fontWithName:"ComicSans" size:20]
label.htmlText = "hello <font size=20>world"

"world" is not in ComicSans

**Comment by mattdonnelly** [comment]
Comic Sans is not installed on iOS: http://iosfonts.com

**Comment by yestoall** [comment]
it's only a funny example... try with another font

label.font = [UIFont fontWithName:"HelveticaNeue-Black" size:20]
label.htmlText = "hello world"

"hello" is HelveticaNeue-Black but "world" is default font

**Comment by mattdonnelly** [comment]
I'm not actually able to recreate this for some reason. Any font I specify gets properly applied to the text. Could this be a problem with RubyMotion possibly?

**Comment by yestoall** [comment]
so, maybe is a rubymotion problem... 

excellent work
with a lot of testing finished the memory problems are history :)

**Comment by mattdonnelly** [comment]
Glad to hear it. I'll close this issue for now
