### ISSUE TITLE
Delegate no working in version 0.0.6?

### ISSUE THREAD

**Issue by cannyboy** [mattdonnelly/MDHTMLLabel#11]
I've just updated MDHTMLLabel via cocoapods, and it seems that didSelectLinkWithURL is no longer being called?

I've set the delegate with`self.htmlMessage.delegate = self;` .. I'm using MDHTMLLabel in a xib, with an IBOutlet.

**Comment by mattdonnelly** [comment]
Oh strange. Would you be able to send me a project demonstrating the problem?

**Comment by cannyboy** [comment]
https://www.dropbox.com/s/581otlhbgp0cvhi/LabelTest.zip

**Comment by mattdonnelly** [comment]
Ah you're absolutely right, but I know how to fix it. I'll post a fix for it shortly

**Comment by mattdonnelly** [comment]
Just pushed a fix for this issue. I'll be submitting it to CocoaPods now too

**Comment by mattdonnelly** [comment]
Should be on cocoapods now as version 1.0 (about time I released a 1.0 version)
