### ISSUE TITLE
certain HTML will cause out of memory errors, infinite loop

### ISSUE THREAD

**Issue by sspitzer** [mattdonnelly/MDHTMLLabel#13]
MDHTMLLabel is great, thank you!

But HTML like this will cause problems:

```
<a href='http://www.google.com'>google.com</a>
```

On my console:

MyApp(2800,0x44df1a8) malloc: **\* mach_vm_map(size=925696) failed (error code=3)
error: can't allocate region
set a breakpoint in malloc_error_break to debug
MyApp(2800,0x44df1a8) malloc: **\* mach_vm_map(size=925696) failed (error code=3)
error: can't allocate region
set a breakpoint in malloc_error_break to debug
ShopStyle_Dev(2800,0x44df1a8) malloc: **\* mach_vm_map(size=925696) failed (error code=3)
error: can't allocate region
set a breakpoint in malloc_error_break to debug
MyApp(2800,0x44df1a8) malloc: **\* mach_vm_map(size=618496) failed (error code=3)
error: can't allocate region
set a breakpoint in malloc_error_break to debug

We'll run out of memory.

looks like [MDHTMLLabel detectURLsInText] has a bug and we get stuck incorrectly wrapping a url over and over.

I've got a patch, I'll make a pull request to see what you think.

**Comment by sspitzer** [comment]
Part of the problem might be that NSDataDetector detects that inner google.com as a link (and wants to replace it with http://google.com, but in this scenario, insideHref and wrappedInAnchors both evaluate to NO.  

Note that my fix will turn the problematic HTML into:

```
<a href='http://www.google.com'><a href='http://google.com'>http://google.com</a></a>
```

Let me know what you think.

**Comment by mattdonnelly** [comment]
Hi, this look good to me. I'll accept the pull request now
