### ISSUE TITLE
Standalone MDHTMLLabel in UITableViewCell not working ?

### ISSUE THREAD

**Issue by koenvanderdrift** [mattdonnelly/MDHTMLLabel#2]
I'm unable to get MDHTMLLabel to work in a custom UITableViewCell. I'm trying to show a plain url, without tags. The text shows up, but it is not clickable, and the delegate is not called. I've created a small test app to demonstrate this: https://dl.dropboxusercontent.com/u/41198645/TestLabel.zip.

**Comment by mattdonnelly** [comment]
Thanks for pointing this out. The problem was being caused by an error in my URL detection code. I'll post a commit now that fixes it
