### ISSUE TITLE
Mixing fonts in link

### ISSUE THREAD

**Issue by cannyboy** [mattdonnelly/MDHTMLLabel#3]
I want to be able to have a label with attributed text, with combined fonts. In my case, I would be using a normal font and a custom symbol font.

For instance, the text:

```
See your items in the (*) Favorites section
```

.. with `(*) Favorites` being a single link and `(*)` being a letter from a custom font.

Is there a way to do this with MDHTMLLabel?

**Comment by mattdonnelly** [comment]
Will be pushing a commit soon with support for the <font> tag which will allow you to combine different fonts
