### ISSUE TITLE
Disabled email detection

### ISSUE THREAD

**Issue by nicopuri** [mattdonnelly/MDHTMLLabel#31]
Can I configured the Label to not detect the emails because it is adding the "mailto:" and don't want this.

Thanks

**Comment by kutakmir** [comment]
did you manage to resolve this issue?

**Comment by ompagi** [comment]
@nicopuri Hi , did you manage to resolve this issue ?

**Comment by DavidFafinski** [comment]
Did anyone managed to resolve this issue ?!

**Comment by DavidFafinski** [comment]
Well, I did my own fix, it's not elegant, but in the "detectURLsInText" method, I simply remove every "mailto:" by replacing it with an empty "" 

See this lines around 1672 :
```
NSString *wrappedURL = [NSString stringWithFormat:@"<a href='%@'>%@</a>", match.URL.absoluteString, [match.URL.absoluteString stringByReplacingOccurrencesOfString:@"mailto:" withString:@""]];
                text = [text stringByReplacingCharactersInRange:match.range
                                                     withString:wrappedURL];
```
