### ISSUE TITLE
NSLineBreakByTruncatingTail showing only one line

### ISSUE THREAD

**Issue by Macjon** [mattdonnelly/MDHTMLLabel#7]
When I add the line break mode NSLineBreakByTruncatingTail, the label is only showing one line of the text. But the label has enough space to view 3 lines and truncate only the last line of text.
(see image, red is the MDHTMLLabel with NSLineBreakByTruncatingTail)

![screen shot 2013-12-05 at 14 08 59](https://f.cloud.github.com/assets/538002/1682636/d8af0554-5dae-11e3-8a8f-494df79b3856.png)

**Comment by mattdonnelly** [comment]
Aware of this issue and am currently looking into it. Need to change a lot of the code to get it work though so it I'll take some time for me to add it.
