### ISSUE TITLE
<font size='XX'>

### ISSUE THREAD

**Issue by yestoall** [mattdonnelly/MDHTMLLabel#8]
font size without font face doesn't work

**Comment by mattdonnelly** [comment]
Ah you're right. Silly mistake on my part. Will push a fix for this now

**Comment by yestoall** [comment]
thanks, i’m always right ;)
-- nacho rapallo

From: Matt Donnelly Matt Donnelly
Reply: mattdonnelly/MDHTMLLabel reply@reply.github.com
Date: 5 Dec 2013 at 17:09:24  
To: mattdonnelly/MDHTMLLabel mdhtmllabel@noreply.github.com
Subject:  Re: [MDHTMLLabel](#8)  
Ah you're right. Silly mistake on my part. Will push a fix for this now
